server:
  port: 9001
spring:
  application:
    name: svca-service
  cloud: 
    bus: 
      trace:
        #启用总线事件跟踪
        enabled: true
  profiles:
    active: dev
  sleuth:
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
    sampler:
      percentage: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
    stream:
      bindings:
        sleuth:
          destination: sleuth-jyl
name: 陈林A
management:
  security:
    enabled: false
  health:
      rabbit:
        enabled: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      fallback: 
        isolation: 
          semaphore: 
            maxConcurrentRequests: 3
      execution:
        timeout: 
          enabled: true
        isolation:
          strategy: THREAD 
          thread:
            timeoutInMilliseconds: 3000
            #设置HystrixCommand.run()的执行是否在超时发生时被中断
            interruptOnTimeout: true
  threadpool: 
    default: 
      #线程池核心线程数
      coreSize: 10
      #设置线程池最大值
      maximumSize: 20
      #设置BlockingQueue最大的队列值
      maxQueueSize: 10
      #设置队列拒绝的阈值
      queueSizeRejectionThreshold: 5
      #设置滚动的统计窗口被分成的桶（bucket）的数目
      metrics: 
        rollingStats: 
          numBuckets: 10
  stream:
    queue:
      destination: hystrix-jyl
#对某一个服务单独配置
svcb-service: 
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 2000
    MaxAutoRetriesNextServer: 3
#    OkToRetryOnAllOperations: true
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}:${random.int[0,999]}
#    health-check-url-path: ${server.context-path}${management.context-path}/health
#    status-page-url-path: ${server.context-path}${management.context-path}/info
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
#      management.context-path: ${server.context-path}${management.context-path}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8761}/eureka/,http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8762}/eureka/
#svcb-service:
#  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

