server:
  port: 9003
spring:
  application:
    name: svcc-service
  cloud: 
    client: 
      hostname: server3
    bus: 
      trace:
        #启用总线事件跟踪
        enabled: true
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
  sleuth:
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
    sampler:
      percentage: 1
    stream:
      bindings:
        sleuth:
          destination: sleuth-jyl

name: 李四

management:
  security:
    enabled: false
  health:
      rabbit:
        enabled: false
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 3000

hystrix:
  command: 
    default: 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  stream:
    queue:
      destination: hystrix-jyl

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}:${random.int[0,999]}
    hostname: server3
    prefer-ip-address: true
    metadata-map:
      lancher: 0
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8761}/eureka/,http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8762}/eureka/

